DROP TABLE IF EXISTS ims_view;
CREATE TABLE ims_view AS
SELECT
cast(itemcd as varchar(18)),
itemdesc1,
itemdesc2,
baseunit,
baseisstdsell,
baseisstdord,
baseisfractqty,
baseispackunit,
baseupc,
baseupcdesc,
basevolperunit,
  basewgtperunit,
    unit1unit,
   unit1ratio,
   unit1isstdsell,
   unit1isstdord,
   unit1isfractqty,
   unit1ispackunit,
   unit1upc,
   unit1upcdesc,
   unit2unit,
   unit2ratio,
   unit2isstdsell,
   unit2isstdord,
   unit2isfractqty,
   unit2ispackunit,
   unit2upc,
   unit2upcdesc,
   unit3unit,
   unit3ratio,
   unit3isstdsell,
   unit3isstdord,
   unit3isfractqty,
   unit3ispackunit,
   unit3upc,
   unit3upcdesc,
   unit4unit,
   unit4ratio,
   unit4isstdsell,
   unit4isstdord,
   unit4isfractqty,
   unit4ispackunit,
   unit4upc,
   unit4upcdesc,
   listprice,
   sellprice,
   priorlastupdated,
   priorlistprice,
   priorsellprice,
   abccd,
   category,
   color,
   directship,
   dropdate,
   inactivecd,
   itemgroupnbr,
   itemtaxclass,
   itemtypecd,
   leadtime,
   lottype,
   minmarginpct,
   nonstockcostpct,
   notes1,
   notes2,
   notes3,
   printlabel,
   productline,
   seriesname,
   tempdatefrom,
   tempdatethru,
   tempprice,
   updatecd,
   vendorxrefcd,
   vendornbr,
   listpricemarginpct,
   sellpricemarginpct,
   sellpriceroundaccuracy,
   vendorpriceunit,
   vendorfob,
   vendorlistprice,
   vendordiscpct1,
   vendorroundaccuracy,
   vendornetprice,
   vendormarkuppct,
   vendorfreightratecwt,
   vendorlandedbasecost,
   priorvendorpriceunit,
   priorvendorfob,
   priorvendorlistprice,
   priorvendorroundaccuracy,
   priorvendornetprice,
   priorvendormarkuppct,
   priorvendorfreightratecwt,
   priorvendorlandedbasecost,
   poincludeinvendorcost,
   --listprice1                 numeric(9,4),
   --listprice2                 numeric(9,4),
   --listprice3                 numeric(9,4),
   --listprice4                 numeric(9,4),
   --listprice5                 numeric(9,4),
   --sellprice1                 numeric(9,4),
   priorlistprice1,
   --priorlistprice2            numeric(9,4),
   --priorlistprice3            numeric(9,4),
   --priorlistprice4            numeric(9,4),
   --priorlistprice5            numeric(9,4),
   priorsellprice1,
   --priorsellprice2            numeric(9,4),
   --priorsellprice3            numeric(9,4),
   --priorsellprice4            numeric(9,4),
   --priorsellprice5            numeric(9,4),
   futurelist,
   futuresell,
   futurelist1,
   futuresell1,
   cost1,
   priorcost,
   priorcost1,
   futurecost,
   futurecost1,
   vendornbr1,
   vendornbr2,
   --vendornbr3                 numeric(6),
   length,
   width,
   mattype,
   thickness,
   sizeunits,
   fulldesc,
   origin,
   shadevariation,
   application,
   showonwebsite,
   colorcategory,
   showonalysedwards,
   offshade,
   itemcd2,
   water_absorption,
   scratch_resistance,
   frost_resistance,
   chemical_resistance,
   pei_abrasion,
   scof_wet,
   scof_dry,
   breaking_strength,
   samplenbr,
   materialclass_cd,
   stdunit,
   stdratio,
   ordunit,
   ordratio,
   matcategory,
   matstyle,
   moh,
   mfeature,
   price,
   qualitychoice,
   greenfriendly ,
   type,
   subtype,
   icons,
   po_notes,
   pricegroup,
   sr_standard,
   thicknessunit,
   bk_standard,
   inventory_itemcd,
   nm_length,
   nm_width,
   nm_thickness,
   residential,
   lightcommercial,
   commercial,
   pre_consummer,
   pos_consummer,
   lead_point,
   unit1wgtperunit,
   unit2wgtperunit,
   unit3wgtperunit,
   unit4wgtperunit,
   purchaser,
   purchaser2,
   dutypct,
   similar_itemcd1,
   similar_itemcd2,
   similar_itemcd3,
   similar_itemcd4,
   similar_itemcd5,
   similar_itemcd6,
   similar_itemcd7,
   restricted,
   warpage,
   wedging,
   dcof,
   thermal_shock,
   bond_strength
FROM ims;   
COMMIT;   
