package com.bedrosians.bedlogic.domain.item;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * itemColorHue generated by hbm2java
 */
@Entity
@Table(name = "ims_item_color_hue", schema = "public")
public class ColorHue implements java.io.Serializable {

	private Integer id;
	private Item item;
	private String colorHue;

	public ColorHue() {
	}

	public ColorHue(Integer id) {
		this.id = id;
	}

	public ColorHue(Integer id, String colorHue) {
		this.id = id;
		this.colorHue = colorHue;
	}
	
	public ColorHue(String colorHue) {
		this.colorHue = colorHue;
	}

	@JsonIgnore
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_code")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "color_hue", length = 120)
	public String getColorHue() {
		return this.colorHue;
	}

	public void setColorHue(String colorHue) {
		this.colorHue = colorHue;
	}

}
