package com.bedrosians.bedlogic.domain.item;
// Generated Mar 10, 2014 11:44:09 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImsEdge generated by hbm2java
 */
@Entity
@Table(name = "ims_edge", schema = "public")
public class ImsEdge implements java.io.Serializable {

	private String description;
	private Set<ImsNewFeature> imsNewFeatures = new HashSet(0);

	public ImsEdge() {
	}

	public ImsEdge(String description) {
		this.description = description;
	}

	public ImsEdge(String description, Set imsNewFeatures) {
		this.description = description;
		this.imsNewFeatures = imsNewFeatures;
	}

	@Id
	@Column(name = "description", unique = true, nullable = false, length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imsEdge")
	public Set<ImsNewFeature> getImsNewFeatures() {
		return this.imsNewFeatures;
	}

	public void setImsNewFeatures(Set<ImsNewFeature> imsNewFeatures) {
		this.imsNewFeatures = imsNewFeatures;
	}

}
