package com.bedrosians.bedlogic.domain.item;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImsIcon generated by hbm2java
 */
@Entity
@Table(name = "ims_icon", schema = "public")
public class ImsIcon implements java.io.Serializable {

	private String description;
	private Set<ImsNewFeature> imsNewFeatures = new HashSet(0);

	public ImsIcon() {
	}

	public ImsIcon(String description) {
		this.description = description;
	}

	public ImsIcon(String description, Set imsNewFeatures) {
		this.description = description;
		this.imsNewFeatures = imsNewFeatures;
	}

	@Id
	@Column(name = "description", unique = true, nullable = false, length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imsIcon")
	public Set<ImsNewFeature> getImsNewFeatures() {
		return this.imsNewFeatures;
	}

	public void setImsNewFeatures(Set<ImsNewFeature> imsNewFeatures) {
		this.imsNewFeatures = imsNewFeatures;
	}

}
