package com.bedrosians.bedlogic.domain.item;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ImsVendor generated by hbm2java
 */
@Entity
@Table(name = "ims_item_vendor", schema = "public")
public class ImsItemVendor implements java.io.Serializable {

	private long vendorId;
	//private String name;
	//private String name2;
	private String xrefId;
	private String priceUnit;
	private String fob;
	private BigDecimal cost;
	private BigDecimal discountPct;
	private Boolean priceRoundAccuracy;
	private BigDecimal netPrice;
	private Short leadTime;
	private BigDecimal freightRateCwt;
	private BigDecimal dutyPct;
	private Item item;

	public ImsItemVendor() {
	}

	public ImsItemVendor(long vendorId) {
		this.vendorId = vendorId;
	}

	@Id
	@Column(name = "vendor_id", unique = true, nullable = false, precision = 10, scale = 0)
	public long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(long vendorId) {
		this.vendorId = vendorId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "itemcd", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}
	
	/*@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name2", length = 60)
	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}
*/
	@Column(name = "xref_id", length = 60)
	public String getXrefId() {
		return this.xrefId;
	}

	public void setXrefId(String xrefId) {
		this.xrefId = xrefId;
	}

	@Column(name = "price_unit", length = 4)
	public String getPriceUnit() {
		return this.priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	@Column(name = "fob", length = 10)
	public String getFob() {
		return this.fob;
	}

	public void setFob(String fob) {
		this.fob = fob;
	}

	@Column(name = "cost", precision = 9, scale = 4)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "discount_pct", precision = 5)
	public BigDecimal getDiscountPct() {
		return this.discountPct;
	}

	public void setDiscountPct(BigDecimal discountPct) {
		this.discountPct = discountPct;
	}

	@Column(name = "price_round_accuracy", precision = 1, scale = 0)
	public Boolean getPriceRoundAccuracy() {
		return this.priceRoundAccuracy;
	}

	public void setPriceRoundAccuracy(Boolean priceRoundAccuracy) {
		this.priceRoundAccuracy = priceRoundAccuracy;
	}

	@Column(name = "net_price", precision = 9, scale = 4)
	public BigDecimal getNetPrice() {
		return this.netPrice;
	}

	public void setNetPrice(BigDecimal netPrice) {
		this.netPrice = netPrice;
	}

	@Column(name = "lead_time", precision = 4, scale = 0)
	public Short getLeadTime() {
		return this.leadTime;
	}

	public void setLeadTime(Short leadTime) {
		this.leadTime = leadTime;
	}

	@Column(name = "freight_rate_cwt", precision = 9, scale = 4)
	public BigDecimal getFreightRateCwt() {
		return this.freightRateCwt;
	}

	public void setFreightRateCwt(BigDecimal freightRateCwt) {
		this.freightRateCwt = freightRateCwt;
	}

	@Column(name = "duty_pct", precision = 7, scale = 4)
	public BigDecimal getDutyPct() {
		return this.dutyPct;
	}

	public void setDutyPct(BigDecimal dutyPct) {
		this.dutyPct = dutyPct;
	}


}
