package com.bedrosians.bedlogic.domain.item;

// Generated Mar 10, 2014 11:21:27 AM by Hibernate Tools 4.0.0

/**
 * ImsMclass generated by hbm2java
 */
public class ImsMclass implements java.io.Serializable {

	private String materialclassCd;
	private String materialdesc;
	private String rptdesc;

	public ImsMclass() {
	}

	public ImsMclass(String materialclassCd, String materialdesc) {
		this.materialclassCd = materialclassCd;
		this.materialdesc = materialdesc;
	}

	public ImsMclass(String materialclassCd, String materialdesc, String rptdesc) {
		this.materialclassCd = materialclassCd;
		this.materialdesc = materialdesc;
		this.rptdesc = rptdesc;
	}

	public String getMaterialclassCd() {
		return this.materialclassCd;
	}

	public void setMaterialclassCd(String materialclassCd) {
		this.materialclassCd = materialclassCd;
	}

	public String getMaterialdesc() {
		return this.materialdesc;
	}

	public void setMaterialdesc(String materialdesc) {
		this.materialdesc = materialdesc;
	}

	public String getRptdesc() {
		return this.rptdesc;
	}

	public void setRptdesc(String rptdesc) {
		this.rptdesc = rptdesc;
	}

}
