package com.bedrosians.bedlogic.domain.item;

// Generated Mar 10, 2014 11:21:27 AM by Hibernate Tools 4.0.0

/**
 * ImsMaterialStyle generated by hbm2java
 */
public class ImsMaterialStyle implements java.io.Serializable {

	private String description;

	public ImsMaterialStyle() {
	}

	public ImsMaterialStyle(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
