package com.bedrosians.bedlogic.domain.item;

// Generated Mar 10, 2014 11:21:27 AM by Hibernate Tools 4.0.0

/**
 * ImsMaterialType generated by hbm2java
 */
public class ImsMaterialType implements java.io.Serializable {

	private String description;

	public ImsMaterialType() {
	}

	public ImsMaterialType(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
