package com.bedrosians.bedlogic.domain.item;
// Generated Mar 10, 2014 11:44:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ImsOrigin generated by hbm2java
 */
@Entity
@Table(name = "ims_origin", schema = "public")
public class ImsOrigin implements java.io.Serializable {

	private String origin;

	public ImsOrigin() {
	}

	public ImsOrigin(String origin) {
		this.origin = origin;
	}

	@Id
	@Column(name = "origin", unique = true, nullable = false, length = 18)
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

}
